### ISSUE TITLE
Failover provider script fails on one of two devices

### ISSUE THREAD

**Issue by edwoodjrjr** [F5Networks/f5-azure-arm-templates#131]
## Do you already have an issue opened with F5 support?
No

## Description
Describe the problem you're having or the enhancement you'd like to request.
When using the failover-api template, seeing this error in /var/log/cloud/azure/failover.log on only the first device in the cluster:

failover.log
2019-06-25T14:02:38.825Z info:  Location: westus2 
2019-06-25T14:02:41.983Z warn:   {"message":"connect EHOSTUNREACH 13.77.184.64:443","stack":"Error: connect EHOSTUNREACH 13.77.184.64:443\n    at Object._errnoException (util.js:1022:11)\n    at _exceptionWithHostPort (util.js:1044:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)","code":"EHOSTUNREACH","errno":"EHOSTUNREACH","syscall":"connect","address":"13.77.184.64","port":443}
2019-06-25T14:02:41.985Z error:  Failover failed: connect EHOSTUNREACH 13.77.184.64:443 
2019-06-25T14:04:42.469Z info:  Location: westus2 
2019-06-25T14:04:45.583Z warn:   {"message":"connect EHOSTUNREACH 13.77.184.64:443","stack":"Error: connect EHOSTUNREACH 13.77.184.64:443\n    at Object._errnoException (util.js:1022:11)\n    at _exceptionWithHostPort (util.js:1044:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)","code":"EHOSTUNREACH","errno":"EHOSTUNREACH","syscall":"connect","address":"13.77.184.64","port":443}
2019-06-25T14:04:45.584Z error:  Failover failed: connect EHOSTUNREACH 13.77.184.64:443

The second device has no issue routing to Azure, with the same configuration.

## Template
For bugs, enter the template with which you are experiencing issues below.

Failover API templates.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 2

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by edwoodjrjr** [comment]
Tracking with internal issue 1458.

**Comment by jsevedge** [comment]
Initial discovery of the issue turned up a device misconfiguration resulting in the external self IP configured not matching the Azure NIC ipconfig

In my test self_2nic was configured as 192.168.3.10 but ipconfig has 192.168.3.4.

Believe this variable `extSubnetPrivateAddress": "[parameters('externalIpAddressRangeStart')]"`
should become this `"extSubnetPrivateAddress": "extSubnetPrivateAddress": "[parameters('externalIpSelfAddressRangeStart')]"`

Workaround:
- tmsh delete net route default
- tmsh delete net self_2nic
- tmsh create net self self_2nic address x.x.x.x/x vlan external
- tmsh create net route default gw x.x.x.x

**Comment by jsevedge** [comment]
This issue was resolved in https://github.com/F5Networks/f5-azure-arm-templates/releases/tag/v7.0.0.1
