### ISSUE TITLE
Failover not occurring

### ISSUE THREAD

**Issue by dimitrd4** [F5Networks/f5-azure-arm-templates#132]
## Do you already have an issue opened with F5 support? Yes
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

## Description
Describe the problem you're having or the enhancement you'd like to request.

Failover does not occur on virtual NICs on both F5 units:

- Error from active and standby units:

2019-06-25T12:27:27.770Z error:  Error during failover: {"message":"Error: Command failed: /usr/bin/tmsh list sys file ssl-key /CloudLibsLocal/cloudLibsLocalPrivate\n01020036:3: The requested Certificate Key File (/CloudLibsLocal/cloudLibsLocalPrivate) was not found.\n:01020036:3: The requested Certificate Key File (/CloudLibsLocal/cloudLibsLocalPrivate) was not found.\n","stack":"Error: Error: Command failed: /usr/bin/tmsh list sys file ssl-key /CloudLibsLocal/cloudLibsLocalPrivate\n01020036:3: The requested Certificate Key File (/CloudLibsLocal/cloudLibsLocalPrivate) was not found.\n:01020036:3: The requested Certificate Key File (/CloudLibsLocal/cloudLibsLocalPrivate) was not found.\n\n    at childProcess.exec (/config/cloud/azure/node_modules/@f5devcentral/f5-cloud-libs-azure/node_modules/@f5devcentral/f5-cloud-libs/lib/util.js:808:33)\n    at ChildProcess.exithandler (child_process.js:282:5)\n    at emitTwo (events.js:126:13)\n    at ChildProcess.emit (events.js:214:7)\n    at maybeClose (internal/child_process.js:925:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)"}
2019-06-25T12:27:27.771Z error:  Failover failed: Error: Command failed: /usr/bin/tmsh list sys file ssl-key /CloudLibsLocal/cloudLibsLocalPrivate
01020036:3: The requested Certificate Key File (/CloudLibsLocal/cloudLibsLocalPrivate) was not found.
:01020036:3: The requested Certificate Key File (/CloudLibsLocal/cloudLibsLocalPrivate) was not found.
 

## Template
For bugs, enter the template with which you are experiencing issues below.
https://github.com/F5Networks/f5-azure-arm-templates/tree/develop/supported/failover/same-net/via-api/n-nic/existing-stack/byol

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 2

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by edwoodjrjr** [comment]
Hi, thanks for opening this.   Working this issue via F5 support will provide the fastest resolution, but I have one question.  Were these BIG-IP devices upgraded from a previous version of BIG-IP?

**Comment by dimitrd4** [comment]
Thanks Mike! I’ve opened a case with F5 and will work with their engineer later today! Indeed, I have upgraded to version 14.1.0, but I can revert to version 12 if it is necessary. Is there any updated working template version for BYOL Active/Standby scenario?

Thank you and have a nice day!


Denislav Dimitrov
Network Security Engineer, Information Technology PPD
Sofia, Bulgaria
denislav.dimitrov2@ppdi.com<mailto:denislav.dimitrov2@ppdi.com>

**Comment by edwoodjrjr** [comment]
Hi Denislav, yes, we have updated templates for failover via-api, but they aren't helpful if you need to do an upgrade.  You would need to create a new deployment with the new template and migrate the configuration over to it, which is a cleaner way to go if you're amenable to it.

We also just published steps on how to do an upgrade and include all the necessary files to enable failover to work:  https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/existing-stack/byol#post-deployment-configuration-steps

You'd want to do one device at a time to verify that things work as expected before completing the upgrade.
Mike

**Comment by shyawnkarim** [comment]
Closing. Please reopen if you still need assistance.
